import Head from "next/head";
import Link from "next/link";
import { QuestionWizard } from "~/components/create/QuestionWizard";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quizzer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <QuestionWizard />
      </main>
    </>
  );
}
