import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Play } from "~/components/play/Play";

const StartPage: NextPage = () => {
  const router = useRouter();
  const { pin } = router.query;

  return (
    <>
      <Head>
        <title>Quizzer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Play pin={(pin as string) ?? undefined} />
    </>
  );
};

export default StartPage;
