import Head from "next/head";
import { useEffect } from "react";
import { io } from "socket.io-client";
import type { GetStaticProps, NextPage } from "next";
import { Start } from "~/components/start/Start";
import { api } from "~/utils/api";
import { Play } from "~/components/play/Play";

const StartPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Quizzer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-200">
        <Play />
      </main>
    </>
  );
};

export default StartPage;
