import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { SavedDraftWrapper } from "~/components/create/SavedDraftWrapper";

const Create: NextPage<{ id: string }> = ({ id }) => {
  return (
    <>
      <Head>
        <title>Quizzer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <SavedDraftWrapper id={id} />
    </>
  );
};

export const getStaticProps: GetStaticProps = (context) => {
  const id = context.params?.id;

  if (typeof id !== "string") {
    throw new Error("no id");
  }
  return {
    props: {
      id,
    },
  };
};

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export default Create;
